# Generated by Django 4.0.5 on 2023-02-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_logo', models.ImageField(null=True, upload_to='logo/')),
            ],
        ),
        migrations.CreateModel(
            name='Student_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('s_name', models.CharField(max_length=100)),
                ('s_email', models.EmailField(max_length=254)),
                ('s_mobile', models.CharField(max_length=12)),
                ('s_address', models.TextField()),
                ('c_desc', models.TextField()),
                ('c_amt', models.PositiveIntegerField()),
                ('c_rec_amt', models.PositiveIntegerField()),
                ('c_rec_amt_word', models.TextField()),
                ('c_pen_amt', models.PositiveIntegerField()),
                ('c_due_date', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
